server:
  port: 8010
spring:
  application:
    name: micorservice-simple-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql


logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

## 开启Actuator的health的详细信息展示
management:
  security:
    enabled: false

## 开启Actuator的info的详细信息展示
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

## 开启Actuator的shutdown(关闭应用)
endpoints:
  shutdown:
    enabled: false

# 注册到eureka中

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:                 # true 注册ip false 或者不填 则为hostname
    prefer-ip-address: true #将自己的ip注册到eureka server 若不配置或为false 则表示注册微服务所在操作系统的hostname到eureka server
